### ISSUE TITLE
Javascript writer

### ISSUE THREAD

**Issue by simon-p-r** [jfjlaros/bin-parser#1]
Hi

Are you planning to add a write method for the javascript library?  

Thanks
Simon

**Comment by jfjlaros** [comment]
This functionality was added in November 2015.

**Comment by simon-p-r** [comment]
Would you be open to having a PR which adds some tests for your javascript code, I find it helps document the api better.

**Comment by jfjlaros** [comment]
What does the abbreviation ``PR'' stand for?

**Comment by simon-p-r** [comment]
Pull request,  I will add some tests and commit to project. I think you have written the best binary parser due to the abstraction away from the implementation.

**Comment by jfjlaros** [comment]
Sure, I am open for any contributions. This is my first JavaScript project, your input is more than welcome.
