### ISSUE TITLE
Undocumented trim option

### ISSUE THREAD

**Issue by Smattr** [jfjlaros/bin-parser#10]
**Describe the bug**
Both the [Python sources](https://github.com/jfjlaros/bin-parser/blob/master/python/bin_parser.py#L43) and [JavaScript sources](https://github.com/jfjlaros/bin-parser/blob/master/javascript/index.js#L151) support an option called `trim`. The [overrides section of the docs](http://bin-parser.readthedocs.io/en/latest/types.html#overrides) omits this option.

**Expected behavior**
The `trim` option documented along with `size` and friends.

**Additional context**
Related to https://github.com/openjournals/joss-reviews/issues/766.

**Comment by jfjlaros** [comment]
This option was originally intended for a string of fixed length with a delimited string inside. In a later versions, this functionality is offered by using the `size` and `delimiter` parameters together. The only use left for `trim` is to control the padding character when writing such a field. I think I will remove this option.
