### ISSUE TITLE
Encoding flexibility?

### ISSUE THREAD

**Issue by Smattr** [jfjlaros/bin-parser#12]
This is very nice work, @jfjlaros, and immediately made me think of how I would use this for decoding ELF-like formats and protocol packets. While playing with some toy examples in the course of https://github.com/openjournals/joss-reviews/issues/766, I came up with the following questions I was curious about:

1. A common sub structure you see in binary formats is the length of some data encoded as a preceding integer. E.g. a string preceded by its length as a little endian 32-bit unsigned integer: `'\x11\x00\x00\x00hello world'`. How would one describe the second part of this data? I.e. a field whose size is that of a previously decoded field.
2. How would one describe alternatives for a field? The case I'm thinking about is decoding [CBOR](http://cbor.io) data. An integer has different encodings depending on its value and ideally I would like to describe "the next field is any one of the integer encodings." I don't immediately see how one would represent this for the purposes of *encoding* as opposed to decoding either.
3. How do you express more complex conditionals? E.g. if I have read three fields `a`, `b`, and `c`, how would I express a following field that is only present when all three of these are true (`a and b and c`)? I had some attempts at this but could only manage to trigger exceptions.

**Comment by jfjlaros** [comment]
For question 1: I made an example in 4c73c5b.

**Comment by jfjlaros** [comment]
For question 2: I never considered variable types before, but it was not difficult to implement. See 9e26cb0 for an example.

**Comment by jfjlaros** [comment]
For question 3: This is currently not supported.

Support for more operands like in your example would be easy, but support for arbitrary expressions will require some work. I'll have to think about how to implement this.

**Comment by jfjlaros** [comment]
I think it would be best to add support for nested structures here, perhaps something along these lines:

```yaml
if:
  operands:
    - operands:
        - 1
        - 1
      operator: eq
    - operands:
        - 2
        - 3
      operator: ne
  operator: and
```

**Comment by jfjlaros** [comment]
This seems to be working, see 4f76674 for an example.

**Comment by Smattr** [comment]
Ah nice! I didn't realise many of these had such simple solutions! For (3), a future extension could be to let people more naturally express these using Python syntax. I.e. just write something like:

```
if:
  - '1 == 1 and 2 != 3'
```

and then decode this with something like [Python ast](https://docs.python.org/3/library/ast.html). Looks pretty good for now though.
