### ISSUE TITLE
Please tag version 0.0.20 and create a GitHub release for JOSS submission.

### ISSUE THREAD

**Issue by hainesr** [jfjlaros/bin-parser#18]
For the JOSS submission please could you tag your version 0.0.20 in the code and create a corresponding "Release" in GitHub. See openjournals/joss-reviews#766 for the discussion of this. Thanks!

**Comment by jfjlaros** [comment]
I was planning to do so after I address the comments. Would that be okay?

**Comment by hainesr** [comment]
Yes, I think that's the best course of action. Thanks!

**Comment by jfjlaros** [comment]
I do have to increase the version number to test npm and PyPI. Do you think that would that be a problem?

**Comment by hainesr** [comment]
I presume you can then up the version number for the JOSS submission. Is that right @danielskatz, @arfon
?

**Comment by arfon** [comment]
> I presume you can then up the version number for the JOSS submission. Is that right @danielskatz, @arfon

Yep.

**Comment by jfjlaros** [comment]
I just released version 1.0.0.
