### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by Smattr** [jfjlaros/bin-parser#8]
It looks like the Python implementation is Python2-only. E.g. [indexing the result of `map`](https://github.com/jfjlaros/bin-parser/blob/master/python/bin_parser.py#L157) will not work in Python 3 where `map` returns an iterator. Was the intention for this code to be compatible across both 2 and 3?

Related to https://github.com/openjournals/joss-reviews/issues/766.

**Comment by Smattr** [comment]
@jfjlaros if you're short on time, let me know and I can take a look at addressing this one as I already have a Python 3 environment setup. I think it's important to address this before submission because [Python 2 is due to be EOLed in 2020](https://pythonclock.org).

**Comment by jfjlaros** [comment]
If it would not be too much trouble, yes please.

**Comment by jfjlaros** [comment]
@Smattr I hope you didn't start on the Python 3 compatibility issue yet, I started on this in 9f028dc.

**Comment by Smattr** [comment]
Ah nice! I had started, but was having a bit of difficulty figuring out which variables were meant to be strings and which were byte data. It looks like your changes subsume what I have. I'll test the latest version with Python 3 and report back.

**Comment by jfjlaros** [comment]
@Smattr In b039858 I added changes to the scripts in "extras" and the documentation. All tests pass for Python 2.7 and Python 3.5 on my machine.

**Comment by Smattr** [comment]
Looks great! Things seem to run well under Python 3 for me now.

One issue: tests/test_parser.py defines the method `TestReader.test_var_type_2` twice. I picked this up by running one of my goto sanity checks from the root directory:

```bash
$ find . -iname "*.py" -exec echo "{}" \; -exec python -m pylint --errors-only "{}" \;
...
./tests/test_parser.py
E:199, 4: method already defined line 191 (function-redefined)
...
```
